### ISSUE TITLE
[Feature request] List all enabled services

### ISSUE THREAD

**Issue by siduck** [19742bytes/roonit#1]
Hi there! it would be great if roonit had an argument or such to list all the enabled services , like vsv . 

![image](https://user-images.githubusercontent.com/59060246/125956537-a6dd2385-c059-43c6-a1e5-1dab57910245.png)

**Comment by 19742bytes** [comment]
I'll try my best to implement this feature! Although I am still learning C, so it may take awhile.
![image](https://user-images.githubusercontent.com/87100084/125998008-83b8cadb-3327-4764-ab67-bb33e470a77d.png)

**Comment by 19742bytes** [comment]
I completed it in a very spaghetti way.
